ALTER TABLE "PhieuBanHang" ADD COLUMN "maKH" CHAR(6);
ALTER TABLE "PhieuDichVu" ADD COLUMN "maKH" CHAR(6);

ALTER TABLE "PhieuBanHang"
ADD CONSTRAINT "PhieuBanHang_maKH_fkey"
FOREIGN KEY ("maKH") REFERENCES "KhachHang"("maKH")
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "PhieuDichVu"
ADD CONSTRAINT "PhieuDichVu_maKH_fkey"
FOREIGN KEY ("maKH") REFERENCES "KhachHang"("maKH")
ON DELETE SET NULL ON UPDATE CASCADE;
