version: '3.8'

services:
  # Base PostgreSQL Database for the application
  db:
    image: postgres:15-alpine
    container_name: quan_ly_vang_bac_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: vangbac_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Next.js Frontend Application
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: quan_ly_vang_bac_fe
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:password123@db:5432/vangbac_db?schema=public
    depends_on:
      - db

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: quan_ly_vang_bac_be
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://admin:password123@db:5432/vangbac_db?schema=public
    depends_on:
      - db

volumes:
  db_data:
